# ports: HOST:CONTAINER

version: '3.8'
services:
  mongo:
    image: mongo
    container_name: ${APP_NAME}-mongo
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./mongo/data:/data/db
    networks:
      - revers-proxy
      - internal

  go:
    build: .
    container_name: ${APP_NAME}-go
    restart: unless-stopped
    dns:
      - 178.22.122.100
    environment:
      - VIRTUAL_HOST=${APP_URL}
      - VIRTUAL_PORT=80
    depends_on:
      - mongo
    networks:
      - revers-proxy
      - internal


networks:
  revers-proxy:
    external: true
    name: nginx-proxy-net
  internal:
    driver: bridge
