swagger: "2.0"
info:
  title: GTC
  description: Golestan auto Take Course.
  version: 1.0.1
host: gtc.m3m.dev
basePath: /
schemes:
  - https

paths:
  /buyCode:
    post:
      summary: buy a new active code or Send previous active code as SMS to buyer phone
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                phone:
                  type: string
              example:
                phone: 09221231213
      responses:
        '200':
          description: payment link or sent SMS.
          content:
            application/json:
              schema:
                type: object
                properties:
                  hasCode:
                    type: boolean
                  payLink:
                    type: string
                  daysLeft:
                    type: integer
                example:
                  hasCode: false
                  payLink: "https://idpay.ir/p/a686fa252d61c7068839d716e0e2feff"
                  daysLeft: 0
        '400':
          description: wrong input.
        '500':
          description: internal server error.

  /isActiveCodeValid:
    post:
      summary: check if active code still validate
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                code:
                  type: string
              example:
                code: 14253614
      responses:
        '200':
          description: code status and remaining days.
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValid:
                    type: boolean
                  daysLeft:
                    type: integer
                example:
                  isValid: true
                  daysLeft: 4
        '400':
          description: wrong input.
        '500':
          description: internal server error.